<a href="https://colab.research.google.com/github/paulanavarretec/RecSys/blob/master/wineRec_OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Representación para el training

Obtenemos un subset pequeño del dataset desde http://www.cellartracker.com, obtenemos los archivos ........

La forma más facil de utilizar esta clase es representando la training data como listas de Python dict objects, donde los dict elements mapean las variables categóricas y numericas de cada intancia a sus valores. Luego usamos DictVectorizer de sklearn  para convertirlas en una disign matrix encodeada con one-of-K or “one-hot” coding.

Un pequeño ejemplo:

In [0]:
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving Reviews.csv to Reviews.csv

In [0]:
reviews = pd.read_csv('Reviews.csv',
                         sep=';',
                         names = ['userID','review', 'review_URL','score','sentiment','sate', 
                                  'vintage', 'type', 'producer', 'variety', 'designation', 'vineyard', 
                                  'country', 'region', 'subregion', 'appellation', 'Pprice_level'],
                         header=0)


print("Matrix size",reviews.shape)

# view columns using df.columns
print("Column Names:",reviews.columns)

print(reviews.dtypes)


#reviews.head()
reviews.tail()

Matrix size (20000, 17)
Column Names: Index(['userID', 'review', 'review_URL', 'score', 'sentiment', 'sate',
       'vintage', 'type', 'producer', 'variety', 'designation', 'vineyard',
       'country', 'region', 'subregion', 'appellation', 'Pprice_level'],
      dtype='object')
userID           object
review           object
review_URL       object
score           float64
sentiment        object
sate             object
vintage         float64
type             object
producer         object
variety          object
designation      object
vineyard         object
country          object
region           object
subregion        object
appellation      object
Pprice_level      int64
dtype: object

,userID,review,review_URL,score,sentiment,sate,vintage,type,producer,variety,designation,vineyard,country,region,subregion,appellation,Pprice_level
19995,Anonymous,Very sweet extracted wine. This was drinakable...,https://www.cellartracker.com/notes.asp?iWine=...,82.0,Anonymous wrote:,11/27/2006 - \nAnonymous wrote: \n\n82 Points,2004.0,Red,Mad Dogs & English Men,Red Blend,NaN,NaN,Spain,Extremadura,NaN,Vino de la Tierra Extremadura,1
19996,msinger,This wine was nothing special - a pizza wine f...,https://www.cellartracker.com/notes.asp?iWine=...,NaN,msinger wrote:,6/28/2006 - \nmsinger wrote:,2004.0,Red,Mad Dogs & English Men,Red Blend,NaN,NaN,Spain,Extremadura,NaN,Vino de la Tierra Extremadura,1
19997,jrglm,Yuck,https://www.cellartracker.com/notes.asp?iWine=...,75.0,jrglm wrote:,3/22/2006 - \njrglm wrote: \n\n75 Points,2004.0,Red,Mad Dogs & English Men,Red Blend,NaN,NaN,Spain,Extremadura,NaN,Vino de la Tierra Extremadura,1
19998,bottlestopper,yuck! Old and well past its best,https://www.cellartracker.com/notes.asp?iWine=...,NaN,bottlestopper wrote:,7/10/2011 - \nbottlestopper wrote:,2003.0,Red,Mad Dogs & English Men,Red Blend,NaN,NaN,Spain,Extremadura,NaN,Vino de la Tierra Extremadura,1
19999,Slipknot,whatever,https://www.cellartracker.com/notes.asp?iWine=...,80.0,Slipknot wrote:,11/15/2006 - \nSlipknot wrote: \n\n80 Points,2003.0,Red,Mad Dogs & English Men,Red Blend,NaN,NaN,Spain,Extremadura,NaN,Vino de la Tierra Extremadura,1

In [0]:
# limit to categorical data using df.select_dtypes()
reviews_categorical = reviews.select_dtypes(include=[object])

reviews['userID'] = reviews['userID'].astype('str')
print(reviews.dtypes)

reviews_categorical.tail(3)

userID           object
review           object
review_URL       object
score           float64
sentiment        object
sate             object
vintage         float64
type             object
producer         object
variety          object
designation      object
vineyard         object
country          object
region           object
subregion        object
appellation      object
Pprice_level      int64
dtype: object

,userID,review,review_URL,sentiment,sate,type,producer,variety,designation,vineyard,country,region,subregion,appellation
19997,jrglm,Yuck,https://www.cellartracker.com/notes.asp?iWine=...,jrglm wrote:,3/22/2006 - \njrglm wrote: \n\n75 Points,Red,Mad Dogs & English Men,Red Blend,NaN,NaN,Spain,Extremadura,NaN,Vino de la Tierra Extremadura
19998,bottlestopper,yuck! Old and well past its best,https://www.cellartracker.com/notes.asp?iWine=...,bottlestopper wrote:,7/10/2011 - \nbottlestopper wrote:,Red,Mad Dogs & English Men,Red Blend,NaN,NaN,Spain,Extremadura,NaN,Vino de la Tierra Extremadura
19999,Slipknot,whatever,https://www.cellartracker.com/notes.asp?iWine=...,Slipknot wrote:,11/15/2006 - \nSlipknot wrote: \n\n80 Points,Red,Mad Dogs & English Men,Red Blend,NaN,NaN,Spain,Extremadura,NaN,Vino de la Tierra Extremadura

In [0]:
reviews['vintage'] = reviews['vintage'].fillna(0).astype('int')

print(reviews.dtypes)

print("Matrix size",reviews.shape)

# import preprocessing from sklearn
from sklearn import preprocessing

# view columns using df.columns
print("Column Names:",reviews.columns)
print(type(reviews))

#reviews = reviews.Reviews.unique()
#print("Unique items Matrix size",reviews.shape)

userID           object
review           object
review_URL       object
score           float64
sentiment        object
sate             object
vintage           int64
type             object
producer         object
variety          object
designation      object
vineyard         object
country          object
region           object
subregion        object
appellation      object
Pprice_level      int64
dtype: object
Matrix size (20000, 17)
Column Names: Index(['userID', 'review', 'review_URL', 'score', 'sentiment', 'sate',
       'vintage', 'type', 'producer', 'variety', 'designation', 'vineyard',
       'country', 'region', 'subregion', 'appellation', 'Pprice_level'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>

Nuestro review df variable contiene un pandas dataframe con 20800 reviews rows y 17 columns con wines features. Todas excepto score, year y vintage son categorical features which will need to be transformed in order to use as inputs in the various machine learning algorithms. Let’s now perform one hot encoding on these categorical variables.

In [0]:
from sklearn.preprocessing import LabelEncoder

le_color = LabelEncoder()
le_make = LabelEncoder()

reviews['type_encoded'] = le_color.fit_transform(reviews.type)
reviews['producer_encoded'] = le_color.fit_transform(reviews.producer)
reviews['variety_encoded'] = le_color.fit_transform(reviews.variety)

print(reviews.dtypes)

reviews.tail(3)

userID               object
review               object
review_URL           object
score               float64
sentiment            object
sate                 object
vintage               int64
type                 object
producer             object
variety              object
designation          object
vineyard             object
country              object
region               object
subregion            object
appellation          object
Pprice_level          int64
type_encoded          int64
producer_encoded      int64
variety_encoded       int64
dtype: object

,userID,review,review_URL,score,sentiment,sate,vintage,type,producer,variety,designation,vineyard,country,region,subregion,appellation,Pprice_level,type_encoded,producer_encoded,variety_encoded
19997,jrglm,Yuck,https://www.cellartracker.com/notes.asp?iWine=...,75.0,jrglm wrote:,3/22/2006 - \njrglm wrote: \n\n75 Points,2004,Red,Mad Dogs & English Men,Red Blend,NaN,NaN,Spain,Extremadura,NaN,Vino de la Tierra Extremadura,1,2,1041,188
19998,bottlestopper,yuck! Old and well past its best,https://www.cellartracker.com/notes.asp?iWine=...,NaN,bottlestopper wrote:,7/10/2011 - \nbottlestopper wrote:,2003,Red,Mad Dogs & English Men,Red Blend,NaN,NaN,Spain,Extremadura,NaN,Vino de la Tierra Extremadura,1,2,1041,188
19999,Slipknot,whatever,https://www.cellartracker.com/notes.asp?iWine=...,80.0,Slipknot wrote:,11/15/2006 - \nSlipknot wrote: \n\n80 Points,2003,Red,Mad Dogs & English Men,Red Blend,NaN,NaN,Spain,Extremadura,NaN,Vino de la Tierra Extremadura,1,2,1041,188

In [0]:

from sklearn.preprocessing import OneHotEncoder

type_ohe = OneHotEncoder()
producer_ohe = OneHotEncoder()
variety_ohe = OneHotEncoder()
designation_ohe = OneHotEncoder()
vineyard_ohe = OneHotEncoder()
country_ohe = OneHotEncoder()
region_ohe = OneHotEncoder()
subregion_ohe = OneHotEncoder()
appellation_ohe = OneHotEncoder()

type_ = type_ohe.fit_transform(reviews.type_encoded.values.reshape(-1,1)).toarray()
producer_ = producer_ohe.fit_transform(reviews.producer_encoded.values.reshape(-1,1)).toarray()
variety_ = variety_ohe.fit_transform(reviews.variety_encoded.values.reshape(-1,1)).toarray()

typeOneHot = pd.DataFrame(type_, columns = ["Producer_"+str(int(i)) for i in range(type_.shape[1])])
producerOneHot = pd.DataFrame(producer_, columns = ["Producer_"+str(int(i)) for i in range(producer_.shape[1])])


df = pd.concat([reviews, typeOneHot,producerOneHot], axis=1)

df.tail(3)

,userID,review,review_URL,score,sentiment,sate,vintage,type,producer,variety,...,Producer_1208,Producer_1209,Producer_1210,Producer_1211,Producer_1212,Producer_1213,Producer_1214,Producer_1215,Producer_1216,Producer_1217
19997,jrglm,Yuck,https://www.cellartracker.com/notes.asp?iWine=...,75.0,jrglm wrote:,3/22/2006 - \njrglm wrote: \n\n75 Points,2004,Red,Mad Dogs & English Men,Red Blend,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19998,bottlestopper,yuck! Old and well past its best,https://www.cellartracker.com/notes.asp?iWine=...,NaN,bottlestopper wrote:,7/10/2011 - \nbottlestopper wrote:,2003,Red,Mad Dogs & English Men,Red Blend,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19999,Slipknot,whatever,https://www.cellartracker.com/notes.asp?iWine=...,80.0,Slipknot wrote:,11/15/2006 - \nSlipknot wrote: \n\n80 Points,2003,Red,Mad Dogs & English Men,Red Blend,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0